version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  inngest:
    image: inngest/inngest:latest
    command: "inngest dev -u http://host.docker.internal:3010/api/inngest"
    ports:
      - "8288:8288"
    environment:
      - INNGEST_LOG_LEVEL=info
